### ISSUE TITLE
Assertion result is immutable

### ISSUE THREAD

**Issue by johnsickels** [flagpolejs/flagpole#183]
While using the `.schema('@name')` method

```
(node:62785) UnhandledPromiseRejectionWarning: Error: Assertion result is immutable.
    at Assertion.execute (/Users/john.sickels/code/cape-canaveral/node_modules/flagpole/dist/assertion.js:540:19)
    at Assertion._executeSchema (/Users/john.sickels/code/cape-canaveral/node_modules/flagpole/dist/assertion.js:585:21)
    at Assertion.<anonymous> (/Users/john.sickels/code/cape-canaveral/node_modules/flagpole/dist/assertion.js:522:25)
    at Generator.next (<anonymous>)
    at /Users/john.sickels/code/cape-canaveral/node_modules/flagpole/dist/assertion.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/john.sickels/code/cape-canaveral/node_modules/flagpole/dist/assertion.js:4:12)
    at Assertion.schema (/Users/john.sickels/code/cape-canaveral/node_modules/flagpole/dist/assertion.js:507:16)
    at /Users/john.sickels/code/cape-canaveral/build/lib/test/flagpole/api-endpoints.js:275:30
    at step (/Users/john.sickels/code/cape-canaveral/build/lib/test/flagpole/api-endpoints.js:33:23)
    at Object.next (/Users/john.sickels/code/cape-canaveral/build/lib/test/flagpole/api-endpoints.js:14:53)
    at /Users/john.sickels/code/cape-canaveral/build/lib/test/flagpole/api-endpoints.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/john.sickels/code/cape-canaveral/build/lib/test/flagpole/api-endpoints.js:4:12)
    at AssertionContext.<anonymous> (/Users/john.sickels/code/cape-canaveral/build/lib/test/flagpole/api-endpoints.js:270:106)
    at /Users/john.sickels/code/cape-canaveral/node_modules/flagpole/dist/scenario.js:694:41
(node:62785) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:62785) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by johnsickels** [comment]
We were not `await`ing on a chained assertion:
```js
context // <--- missing await
  .assert(context.response.body)
  .contains('null')
  .schema('@agents-events-no-param-api');
```
